baseURL = "https://jacabreu.github.io/"
languageCode = "pt-br"
title = "Casa da Jac"
#theme = "ananke"
#theme="hugo-theme-prav"
#theme= "hugo-PaperMod"
theme="hugo-kiera"

#[params]
#  title = "casa da Jac"
#  tagline = "Aprendizados e pensamentos da Jac"
#  author = "Jacqueline Abreu"
#  authorBlurb = "Software Developer. Pessoa aleatória."
  
#[social]
#  email = "mailto:example@example.com"
#  github = "https://github.com/JacAbreu"
#  linkedin = "https://linkedin.com/in/jacabreu"

pygmentsCodeFences = true

[author]
    name = "Jac Abreu"           #Author name
    github = "JacAbreu/"         #Github username
    gitlab = ""         #Gitlab username
    linkedin = ""       #LinkedIn username
    twitter = ""        #Twitter username
    stackoverflow = ""  #StackOverflow username
    devto = "jacabreu"          #Dev.to username 

[params]
    tagline = "Aprendizados e pensamentos da Jac"
    customCSS = []  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode
    
menu = "main"
meta = "false"
title = "Posts"
weight = "10"    
